
about :
  name : Documentation

submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master
  Logger : git+https:///github.com/Wandalen/wLogger.git/out/wLogger#master
  LoggerToJs : git+https:///github.com/Wandalen/wLoggerToJs.git/out/wLoggerToJs#master
  Consequence : git+https:///github.com/Wandalen/wConsequence.git/out/wConsequence#master
  Instancing : git+https:///github.com/Wandalen/wInstancing.git/out/wInstancing#master
  EventHandler : git+https:///github.com/Wandalen/wEventHandler.git/out/wEventHandler#master
  Copyable : git+https:///github.com/Wandalen/wCopyable.git/out/wCopyable#master
  FieldsStack : git+https:///github.com/Wandalen/wFieldsStack.git/out/wFieldsStack#master
  Looker : git+https:///github.com/Wandalen/wLooker.git/out/wLooker#master
  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master
  Proto : git+https:///github.com/Wandalen/wProto.git/out/wProto#master
  Selector : git+https:///github.com/Wandalen/wSelector.git/out/wSelector#master

  Stringer : git+https:///github.com/Wandalen/wStringer.git/out/wStringer#master
  ArraySorted : git+https:///github.com/Wandalen/wArraySorted.git/out/wArraySorted#master
  ArraySparse : git+https:///github.com/Wandalen/wArraySparse.git/out/wArraySparse#master
  ExternalFundamentals : git+https:///github.com/Wandalen/wExternalFundamentals.git/out/wExternalFundamentals#master
  UriFundamentals : git+https:///github.com/Wandalen/wUriFundamentals.git/out/wUriFundamentals#master
  Comparator : git+https:///github.com/Wandalen/wComparator.git/out/wComparator#master

  LookerExtra : git+https:///github.com/Wandalen/wLookerExtra.git/out/wLookerExtra#master
  Traverser : git+https:///github.com/Wandalen/wTraverser.git/out/wTraverser#master
  WebUriFundamentals : git+https:///github.com/Wandalen/wWebUriFundamentals.git/out/wWebUriFundamentals#master
  Cloner : git+https:///github.com/Wandalen/wCloner.git/out/wCloner#master
  StringsExtra : git+https:///github.com/Wandalen/wStringsExtra.git/out/wStringsExtra#master
  Procedure : git+https:///github.com/Wandalen/wProcedure.git/out/wProcedure#master

  Bitmask : git+https:///github.com/Wandalen/wBitmask.git/out/wBitmask#master
  RegexpObject : git+https:///github.com/Wandalen/wRegexpObject.git/out/wRegexpObject#master
  Color : git+https:///github.com/Wandalen/wColor.git/out/wColor#master
  Color256 : git+https:///github.com/Wandalen/wColor256.git/out/wColor256#master
  ChangeTransactor : git+https:///github.com/Wandalen/wChangeTransactor.git/out/wChangeTransactor#master
  Vocabulary : git+https:///github.com/Wandalen/wVocabulary.git/out/wVocabulary#master
  CommandsAggregator : git+https:///github.com/Wandalen/wCommandsAggregator.git/out/wCommandsAggregator#master
  CommandsConfig : git+https:///github.com/Wandalen/wCommandsConfig.git/out/wCommandsConfig#master
  Files : git+https:///github.com/Wandalen/wFiles.git/out/wFiles#master
  FilesArchive : git+https:///github.com/Wandalen/wFilesArchive.git/out/wFilesArchive#master
  FilesEncoders : git+https:///github.com/Wandalen/wFilesEncoders.git/out/wFilesEncoders#master
  Verbal : git+https:///github.com/Wandalen/wVerbal.git/out/wVerbal#master
  StateStorage : git+https:///github.com/Wandalen/wStateStorage.git/out/wStateStorage#master
  StateSession : git+https:///github.com/Wandalen/wStateSession.git/out/wStateSession#master
  PathTranslator : git+https:///github.com/Wandalen/wPathTranslator.git/out/wPathTranslator#master
  FileExecutor : git+https:///github.com/Wandalen/wFileExecutor.git/out/wFileExecutor#master
  TranspilationStrategy : git+https:///github.com/Wandalen/wTranspilationStrategy.git/out/wTranspilationStrategy#master
  NameMapper : git+https:///github.com/Wandalen/wNameMapper.git/out/wNameMapper#master
  TemplateTreeResolver : git+https:///github.com/Wandalen/wTemplateTreeResolver.git/out/wTemplateTreeResolver#master
  TemplateTreeEnvironment : git+https:///github.com/Wandalen/wTemplateTreeEnvironment.git/out/wTemplateTreeEnvironment#master
  TemplateFileWriter : git+https:///github.com/Wandalen/wTemplateFileWriter.git/out/wTemplateFileWriter#master
  Graph : git+https:///github.com/Wandalen/wGraphBase.git/out/wGraphBase#master
  Communicator : git+https:///github.com/Wandalen/wCommunicator.git/out/wCommunicator#master
  Starter : git+https:///github.com/Wandalen/wStarter.git/out/wStarter#master

  Testing : git+https:///github.com/Wandalen/wTesting.git/out/wTesting#master
  Willbe : git+https:///github.com/Wandalen/Willbe.git/out/Willbe#master

path :

  docsWillbe : './.module/willbe/doc'
  docsTools : './.module/Tools/doc'
  docsConsequence : './.module/Consequence/doc'
  docsify : './proto/docsify'
  out.debug : './out'
  out.debug.manuals : './out/docs/Manuals'
  out.docs.Willbe : './out/docs/Manuals/willbe'
  out.docs.Tools : './out/docs/Manuals/wTools'
  out.docs.Consequence : './out/docs/Manuals/wConsequence'

reflector :

  reflect.docsify :
    inherit : predefined.*
    filePath :
      path::docsify : path::out.debug
    criterion :
      debug : 1

  reflect.manuals :
    inherit : predefined.*
    filePath :
      "{submodule::*/path::in}/doc" : path::out.debug.manuals*=1
    src :
      basePath : ".module"
      ends : md
    criterion :
      doc : 1

  # reflect.docs.manual :
  #   inherit : predefined.*
  #   filePath :
  #     path::docsWillbe : path::out.docs.Willbe
  #     path::docsTools : path::out.docs.Tools
  #     path::docsConsequence : path::out.docs.Consequence
  #   src :
  #     ends : 'md'
  #   criterion :
  #     debug : 1

step :

  reflect.docsify :
    inherit : predefined.reflect
    reflector :
      reflector::reflect.docsify*=1
    criterion :
      debug : 1

  reflect.manuals :
    inherit : predefined.reflect
    reflector :
      reflector::reflect.manuals*=1
    criterion :
      doc : 1

  # reflect.docs.manual :
  #   inherit : predefined.reflect
  #   reflector :
  #     reflector::reflect.docs.manual*=1
  #   criterion :
  #     debug : 1

  clear.out :
    inherit : predefined.delete
    filePath : path::out.debug

  npm.install :
    currentPath : .
    shell : npm i

  jsdoc.generate :
    currentPath : .
    shell : node proto/js2md/js2md.ss .module

  manualsIndex.generate :
    currentPath : .
    shell : node manualsIndex.ss

  server.start :
    currentPath : .
    shell : node staticserver.ss

  page.open :
    currentPath : .
    shell : node opn.ss

build :

  generate :
    criterion :
      doc : 1
      default : 0
    steps :
      - step::submodules.download
      - step::clear.out
      - step::reflect.docsify*=1
      - step::reflect.manuals*=1
      - step::npm.install*=1
      - step::jsdoc.generate
      - step::manualsIndex.generate

  start :
    criterion :
      doc : 1
      default : 0
    steps :
      - step::page.open
      - step::server.start

  doc :
    criterion :
      doc : 1
      default : 1
    steps :
      - build::generate
      - build::start
