
about :
  name : Documentation

submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master
  Logger : git+https:///github.com/Wandalen/wLogger.git/out/wLogger#master
  LoggerToJs : git+https:///github.com/Wandalen/wLoggerToJs.git/out/wLoggerToJs#master
  Consequence : git+https:///github.com/Wandalen/wConsequence.git/out/wConsequence#master
  Instancing : git+https:///github.com/Wandalen/wInstancing.git/out/wInstancing#master
  EventHandler : git+https:///github.com/Wandalen/wEventHandler.git/out/wEventHandler#master
  Copyable : git+https:///github.com/Wandalen/wCopyable.git/out/wCopyable#master
  FieldsStack : git+https:///github.com/Wandalen/wFieldsStack.git/out/wFieldsStack#master
  Looker : git+https:///github.com/Wandalen/wLooker.git/out/wLooker#master
  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master
  Proto : git+https:///github.com/Wandalen/wProto.git/out/wProto#master
  Selector : git+https:///github.com/Wandalen/wSelector.git/out/wSelector#master

  Stringer : git+https:///github.com/Wandalen/wStringer.git/out/wStringer#master
  ArraySorted : git+https:///github.com/Wandalen/wArraySorted.git/out/wArraySorted#master
  ArraySparse : git+https:///github.com/Wandalen/wArraySparse.git/out/wArraySparse#master
  ExternalFundamentals : git+https:///github.com/Wandalen/wExternalFundamentals.git/out/wExternalFundamentals#master
  UriFundamentals : git+https:///github.com/Wandalen/wUriFundamentals.git/out/wUriFundamentals#master
  Comparator : git+https:///github.com/Wandalen/wComparator.git/out/wComparator#master

  LookerExtra : git+https:///github.com/Wandalen/wLookerExtra.git/out/wLookerExtra#master
  Traverser : git+https:///github.com/Wandalen/wTraverser.git/out/wTraverser#master
  WebUriFundamentals : git+https:///github.com/Wandalen/wWebUriFundamentals.git/out/wWebUriFundamentals#master
  Cloner : git+https:///github.com/Wandalen/wCloner.git/out/wCloner#master
  StringsExtra : git+https:///github.com/Wandalen/wStringsExtra.git/out/wStringsExtra#master
  Procedure : git+https:///github.com/Wandalen/wProcedure.git/out/wProcedure#master

  Bitmask : git+https:///github.com/Wandalen/wBitmask.git/out/wBitmask#master
  RegexpObject : git+https:///github.com/Wandalen/wRegexpObject.git/out/wRegexpObject#master
  Color : git+https:///github.com/Wandalen/wColor.git/out/wColor#master
  Color256 : git+https:///github.com/Wandalen/wColor256.git/out/wColor256#master
  ChangeTransactor : git+https:///github.com/Wandalen/wChangeTransactor.git/out/wChangeTransactor#master
  Vocabulary : git+https:///github.com/Wandalen/wVocabulary.git/out/wVocabulary#master
  CommandsAggregator : git+https:///github.com/Wandalen/wCommandsAggregator.git/out/wCommandsAggregator#master
  CommandsConfig : git+https:///github.com/Wandalen/wCommandsConfig.git/out/wCommandsConfig#master
  Files : git+https:///github.com/Wandalen/wFiles.git/out/wFiles#master
  FilesArchive : git+https:///github.com/Wandalen/wFilesArchive.git/out/wFilesArchive#master
  FilesEncoders : git+https:///github.com/Wandalen/wFilesEncoders.git/out/wFilesEncoders#master
  Verbal : git+https:///github.com/Wandalen/wVerbal.git/out/wVerbal#master
  StateStorage : git+https:///github.com/Wandalen/wStateStorage.git/out/wStateStorage#master
  StateSession : git+https:///github.com/Wandalen/wStateSession.git/out/wStateSession#master
  PathTranslator : git+https:///github.com/Wandalen/wPathTranslator.git/out/wPathTranslator#master
  FileExecutor : git+https:///github.com/Wandalen/wFileExecutor.git/out/wFileExecutor#master
  TranspilationStrategy : git+https:///github.com/Wandalen/wTranspilationStrategy.git/out/wTranspilationStrategy#master
  NameMapper : git+https:///github.com/Wandalen/wNameMapper.git/out/wNameMapper#master
  TemplateTreeResolver : git+https:///github.com/Wandalen/wTemplateTreeResolver.git/out/wTemplateTreeResolver#master
  TemplateTreeEnvironment : git+https:///github.com/Wandalen/wTemplateTreeEnvironment.git/out/wTemplateTreeEnvironment#master
  TemplateFileWriter : git+https:///github.com/Wandalen/wTemplateFileWriter.git/out/wTemplateFileWriter#master
  Graph : git+https:///github.com/Wandalen/wGraphBase.git/out/wGraphBase#master
  Communicator : git+https:///github.com/Wandalen/wCommunicator.git/out/wCommunicator#master
  Starter : git+https:///github.com/Wandalen/wStarter.git/out/wStarter#master

  Testing : git+https:///github.com/Wandalen/wTesting.git/out/wTesting#master
  Willbe : git+https:///github.com/Wandalen/Willbe.git/out/Willbe#master

path :

  out.debug : out
  out.sources : out/sources
  out.doc : out/doc
  concepts : out/concepts
  tutorials : out/tutorials
  wdoc.exec : node_modules/wdocgenerator/proto/dwtools/atop/docgen/Exec2
  node.modules : node_modules
  package.lock : package-lock.json

reflector :

  reflect.concepts :
    inherit : predefined.*
    mandatory : 0
    filePath :
      "{submodule::*/path::in}/doc" : path::concepts
    src :
      basePath : ".module"
      ends : md
    criterion :
      doc : 1

  reflect.tutorials :
    inherit : predefined.*
    mandatory : 0
    filePath :
      "{submodule::*/path::in}/tutorials" : path::tutorials
    src :
      basePath : ".module"
      ends : md
    criterion :
      doc : 1

  reflect.sources :
    inherit : submodule::*/exported::*=1/reflector::exportedFiles*=1
    dst :
      basePath : .
      prefixPath : path::out.sources
    criterion :
      doc : 1

step :

  clean.out :
    inherit : predefined.delete
    filePath : path::out.debug

  clean.node_modules :
    inherit : predefined.delete
    filePath : path::node.modules

  clean.package-lock :
    inherit : predefined.delete
    filePath : path::package.lock

  npm.install :
    currentPath : .
    shell : npm i

  doc.generate :
    currentPath : .
    shell : "node {path::wdoc.exec} .generate {path::out.sources} outPath:{path::out.doc} conceptsPath:{path::concepts} tutorialsPath:{path::tutorials}"

  doc.docsify.run :
    currentPath : path::out.doc
    shell : node staticserver.ss

  doc.view :
    inherit : predefined.view
    filePath : http://127.0.0.1:3000
    delay : 3000

build :

  generate :
    criterion :
      doc : 1
      default : 0
    steps :
      - step::submodules.download
      - step::clean.out
      - step::reflect.concepts*=1
      - step::reflect.tutorials*=1
      - step::reflect.sources
      - step::npm.install*=1
      - step::doc.generate

  start :
    criterion :
      doc : 1
      default : 0
    steps :
      - step::doc.view
      - step::doc.docsify.run

  default :
    criterion :
      doc : 1
      default : 1
    steps :
      - build::generate
      - build::start

  clean :
    steps :
      - step::submodules.clean
      - step::clean.out
      - step::clean.node_modules
      - step::clean.package-lock
