
sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - '8'
  - '9'
  - '10'
  - '12'
  - 'lts/*'
compiler:
  - gcc
  - clang
>>>>>>> c5afb0099bd85e85a841bc23c1a8c4c7f6215660
script:
  - npm test
cache:
  npm: false
